-- Asset universe seed: ~200 tickers (top US stocks + popular ETFs + top crypto)
-- Run after migrations. Idempotent (uses on conflict do nothing).

insert into assets (symbol, name, type, exchange, currency) values
-- Mega-cap tech
('AAPL',  'Apple Inc.',                  'stock', 'NASDAQ', 'USD'),
('MSFT',  'Microsoft Corporation',       'stock', 'NASDAQ', 'USD'),
('GOOGL', 'Alphabet Inc. Class A',       'stock', 'NASDAQ', 'USD'),
('GOOG',  'Alphabet Inc. Class C',       'stock', 'NASDAQ', 'USD'),
('AMZN',  'Amazon.com Inc.',             'stock', 'NASDAQ', 'USD'),
('META',  'Meta Platforms Inc.',         'stock', 'NASDAQ', 'USD'),
('NVDA',  'NVIDIA Corporation',          'stock', 'NASDAQ', 'USD'),
('TSLA',  'Tesla Inc.',                  'stock', 'NASDAQ', 'USD'),
('AVGO',  'Broadcom Inc.',               'stock', 'NASDAQ', 'USD'),
('ORCL',  'Oracle Corporation',          'stock', 'NYSE',   'USD'),
('CRM',   'Salesforce Inc.',             'stock', 'NYSE',   'USD'),
('ADBE',  'Adobe Inc.',                  'stock', 'NASDAQ', 'USD'),
('NFLX',  'Netflix Inc.',                'stock', 'NASDAQ', 'USD'),
('AMD',   'Advanced Micro Devices',      'stock', 'NASDAQ', 'USD'),
('INTC',  'Intel Corporation',           'stock', 'NASDAQ', 'USD'),
('CSCO',  'Cisco Systems Inc.',          'stock', 'NASDAQ', 'USD'),
('IBM',   'International Business Machines', 'stock', 'NYSE', 'USD'),
('QCOM',  'Qualcomm Incorporated',       'stock', 'NASDAQ', 'USD'),
('TXN',   'Texas Instruments',           'stock', 'NASDAQ', 'USD'),
('NOW',   'ServiceNow Inc.',             'stock', 'NYSE',   'USD'),
('SHOP',  'Shopify Inc.',                'stock', 'NYSE',   'USD'),
('UBER',  'Uber Technologies',           'stock', 'NYSE',   'USD'),
('PYPL',  'PayPal Holdings',             'stock', 'NASDAQ', 'USD'),
('SQ',    'Block Inc.',                  'stock', 'NYSE',   'USD'),
('SPOT',  'Spotify Technology',          'stock', 'NYSE',   'USD'),
('SNAP',  'Snap Inc.',                   'stock', 'NYSE',   'USD'),
('PLTR',  'Palantir Technologies',       'stock', 'NYSE',   'USD'),
('COIN',  'Coinbase Global',             'stock', 'NASDAQ', 'USD'),
('RBLX',  'Roblox Corporation',          'stock', 'NYSE',   'USD'),
('MU',    'Micron Technology',           'stock', 'NASDAQ', 'USD'),

-- Financial
('BRK-B', 'Berkshire Hathaway B',        'stock', 'NYSE',   'USD'),
('JPM',   'JPMorgan Chase',              'stock', 'NYSE',   'USD'),
('V',     'Visa Inc.',                   'stock', 'NYSE',   'USD'),
('MA',    'Mastercard Incorporated',     'stock', 'NYSE',   'USD'),
('BAC',   'Bank of America',             'stock', 'NYSE',   'USD'),
('WFC',   'Wells Fargo',                 'stock', 'NYSE',   'USD'),
('GS',    'Goldman Sachs',               'stock', 'NYSE',   'USD'),
('MS',    'Morgan Stanley',              'stock', 'NYSE',   'USD'),
('AXP',   'American Express',            'stock', 'NYSE',   'USD'),
('BLK',   'BlackRock Inc.',              'stock', 'NYSE',   'USD'),
('SCHW',  'Charles Schwab',              'stock', 'NYSE',   'USD'),
('C',     'Citigroup Inc.',              'stock', 'NYSE',   'USD'),

-- Healthcare
('UNH',   'UnitedHealth Group',          'stock', 'NYSE',   'USD'),
('JNJ',   'Johnson & Johnson',           'stock', 'NYSE',   'USD'),
('LLY',   'Eli Lilly and Company',       'stock', 'NYSE',   'USD'),
('PFE',   'Pfizer Inc.',                 'stock', 'NYSE',   'USD'),
('MRK',   'Merck & Co.',                 'stock', 'NYSE',   'USD'),
('ABBV',  'AbbVie Inc.',                 'stock', 'NYSE',   'USD'),
('TMO',   'Thermo Fisher Scientific',    'stock', 'NYSE',   'USD'),
('ABT',   'Abbott Laboratories',         'stock', 'NYSE',   'USD'),
('DHR',   'Danaher Corporation',         'stock', 'NYSE',   'USD'),
('CVS',   'CVS Health',                  'stock', 'NYSE',   'USD'),
('BMY',   'Bristol-Myers Squibb',        'stock', 'NYSE',   'USD'),
('GILD',  'Gilead Sciences',             'stock', 'NASDAQ', 'USD'),

-- Consumer
('WMT',   'Walmart Inc.',                'stock', 'NYSE',   'USD'),
('PG',    'Procter & Gamble',            'stock', 'NYSE',   'USD'),
('KO',    'Coca-Cola Company',           'stock', 'NYSE',   'USD'),
('PEP',   'PepsiCo Inc.',                'stock', 'NASDAQ', 'USD'),
('MCD',   'McDonald''s Corporation',     'stock', 'NYSE',   'USD'),
('NKE',   'Nike Inc.',                   'stock', 'NYSE',   'USD'),
('SBUX',  'Starbucks Corporation',       'stock', 'NASDAQ', 'USD'),
('COST',  'Costco Wholesale',            'stock', 'NASDAQ', 'USD'),
('TGT',   'Target Corporation',          'stock', 'NYSE',   'USD'),
('HD',    'Home Depot',                  'stock', 'NYSE',   'USD'),
('LOW',   'Lowe''s Companies',           'stock', 'NYSE',   'USD'),
('DIS',   'Walt Disney Company',         'stock', 'NYSE',   'USD'),
('CMCSA', 'Comcast Corporation',         'stock', 'NASDAQ', 'USD'),

-- Energy / Industrial
('XOM',   'Exxon Mobil',                 'stock', 'NYSE',   'USD'),
('CVX',   'Chevron Corporation',         'stock', 'NYSE',   'USD'),
('COP',   'ConocoPhillips',              'stock', 'NYSE',   'USD'),
('CAT',   'Caterpillar Inc.',            'stock', 'NYSE',   'USD'),
('BA',    'Boeing Company',              'stock', 'NYSE',   'USD'),
('GE',    'General Electric',            'stock', 'NYSE',   'USD'),
('HON',   'Honeywell International',     'stock', 'NASDAQ', 'USD'),
('UPS',   'United Parcel Service',       'stock', 'NYSE',   'USD'),
('DE',    'Deere & Company',             'stock', 'NYSE',   'USD'),
('LMT',   'Lockheed Martin',             'stock', 'NYSE',   'USD'),
('RTX',   'RTX Corporation',             'stock', 'NYSE',   'USD'),

-- Telecom / Utilities / Real Estate
('T',     'AT&T Inc.',                   'stock', 'NYSE',   'USD'),
('VZ',    'Verizon Communications',      'stock', 'NYSE',   'USD'),
('TMUS',  'T-Mobile US',                 'stock', 'NASDAQ', 'USD'),
('NEE',   'NextEra Energy',              'stock', 'NYSE',   'USD'),

-- Popular meme / retail favorites
('GME',   'GameStop Corp.',              'stock', 'NYSE',   'USD'),
('AMC',   'AMC Entertainment',           'stock', 'NYSE',   'USD'),
('BB',    'BlackBerry Limited',          'stock', 'NYSE',   'USD'),
('HOOD',  'Robinhood Markets',           'stock', 'NASDAQ', 'USD'),
('LCID',  'Lucid Group',                 'stock', 'NASDAQ', 'USD'),
('RIVN',  'Rivian Automotive',           'stock', 'NASDAQ', 'USD'),
('F',     'Ford Motor Company',          'stock', 'NYSE',   'USD'),
('GM',    'General Motors',              'stock', 'NYSE',   'USD'),
('NIO',   'NIO Inc.',                    'stock', 'NYSE',   'USD'),

-- Broad market ETFs
('SPY',   'SPDR S&P 500 ETF',            'etf', 'NYSEARCA', 'USD'),
('VOO',   'Vanguard S&P 500 ETF',        'etf', 'NYSEARCA', 'USD'),
('IVV',   'iShares Core S&P 500',        'etf', 'NYSEARCA', 'USD'),
('VTI',   'Vanguard Total Stock Market', 'etf', 'NYSEARCA', 'USD'),
('VTV',   'Vanguard Value ETF',          'etf', 'NYSEARCA', 'USD'),
('VUG',   'Vanguard Growth ETF',         'etf', 'NYSEARCA', 'USD'),
('VEA',   'Vanguard FTSE Developed',     'etf', 'NYSEARCA', 'USD'),
('VWO',   'Vanguard Emerging Markets',   'etf', 'NYSEARCA', 'USD'),
('VXUS',  'Vanguard Total Intl Stock',   'etf', 'NASDAQ',   'USD'),
('IEFA',  'iShares Core MSCI EAFE',      'etf', 'BATS',     'USD'),
('IEMG',  'iShares Core MSCI Emerging',  'etf', 'NYSEARCA', 'USD'),
('AGG',   'iShares Core US Aggregate Bond','etf','NYSEARCA','USD'),
('BND',   'Vanguard Total Bond Market',  'etf', 'NASDAQ',   'USD'),
('TLT',   'iShares 20+ Year Treasury',   'etf', 'NASDAQ',   'USD'),
('IEF',   'iShares 7-10 Year Treasury',  'etf', 'NASDAQ',   'USD'),
('SHY',   'iShares 1-3 Year Treasury',   'etf', 'NASDAQ',   'USD'),
('TIP',   'iShares TIPS Bond ETF',       'etf', 'NYSEARCA', 'USD'),
('LQD',   'iShares iBoxx Investment Grade', 'etf','NYSEARCA','USD'),
('HYG',   'iShares iBoxx High Yield',    'etf', 'NYSEARCA', 'USD'),

-- Sector ETFs
('XLF',   'Financial Select Sector SPDR','etf', 'NYSEARCA', 'USD'),
('XLK',   'Technology Select Sector SPDR','etf','NYSEARCA', 'USD'),
('XLE',   'Energy Select Sector SPDR',   'etf', 'NYSEARCA', 'USD'),
('XLV',   'Health Care Select Sector SPDR','etf','NYSEARCA','USD'),
('XLI',   'Industrial Select Sector SPDR','etf','NYSEARCA', 'USD'),
('XLY',   'Consumer Discretionary SPDR', 'etf', 'NYSEARCA', 'USD'),
('XLP',   'Consumer Staples SPDR',       'etf', 'NYSEARCA', 'USD'),
('XLB',   'Materials Select Sector SPDR','etf', 'NYSEARCA', 'USD'),
('XLU',   'Utilities Select Sector SPDR','etf', 'NYSEARCA', 'USD'),
('XLRE',  'Real Estate Select Sector SPDR','etf','NYSEARCA','USD'),
('XLC',   'Communication Services SPDR', 'etf', 'NYSEARCA', 'USD'),

-- Tech / growth ETFs
('QQQ',   'Invesco QQQ Trust',           'etf', 'NASDAQ',   'USD'),
('QQQM',  'Invesco NASDAQ-100',          'etf', 'NASDAQ',   'USD'),
('SOXX',  'iShares Semiconductor ETF',   'etf', 'NASDAQ',   'USD'),
('SMH',   'VanEck Semiconductor ETF',    'etf', 'NASDAQ',   'USD'),
('ARKK',  'ARK Innovation ETF',          'etf', 'NYSEARCA', 'USD'),
('ARKG',  'ARK Genomic Revolution',      'etf', 'NYSEARCA', 'USD'),

-- International / alt
('EFA',   'iShares MSCI EAFE',           'etf', 'NYSEARCA', 'USD'),
('EEM',   'iShares MSCI Emerging Markets','etf','NYSEARCA', 'USD'),
('GLD',   'SPDR Gold Shares',            'etf', 'NYSEARCA', 'USD'),
('IAU',   'iShares Gold Trust',          'etf', 'NYSEARCA', 'USD'),
('SLV',   'iShares Silver Trust',        'etf', 'NYSEARCA', 'USD'),
('USO',   'United States Oil Fund',      'etf', 'NYSEARCA', 'USD'),
('DBC',   'Invesco DB Commodity',        'etf', 'NYSEARCA', 'USD'),
('VNQ',   'Vanguard Real Estate',        'etf', 'NYSEARCA', 'USD'),
('VYM',   'Vanguard High Dividend Yield','etf', 'NYSEARCA', 'USD'),
('SCHD',  'Schwab US Dividend Equity',   'etf', 'NYSEARCA', 'USD'),
('DIA',   'SPDR Dow Jones Industrial',   'etf', 'NYSEARCA', 'USD'),
('IWM',   'iShares Russell 2000',        'etf', 'NYSEARCA', 'USD'),
('IJH',   'iShares Core S&P Mid-Cap',    'etf', 'NYSEARCA', 'USD'),
('IJR',   'iShares Core S&P Small-Cap',  'etf', 'NYSEARCA', 'USD'),

-- Top crypto (yfinance format: SYMBOL-USD)
('BTC-USD',  'Bitcoin',                  'crypto', 'CCC', 'USD'),
('ETH-USD',  'Ethereum',                 'crypto', 'CCC', 'USD'),
('USDT-USD', 'Tether',                   'crypto', 'CCC', 'USD'),
('BNB-USD',  'Binance Coin',             'crypto', 'CCC', 'USD'),
('SOL-USD',  'Solana',                   'crypto', 'CCC', 'USD'),
('XRP-USD',  'XRP',                      'crypto', 'CCC', 'USD'),
('USDC-USD', 'USD Coin',                 'crypto', 'CCC', 'USD'),
('ADA-USD',  'Cardano',                  'crypto', 'CCC', 'USD'),
('DOGE-USD', 'Dogecoin',                 'crypto', 'CCC', 'USD'),
('AVAX-USD', 'Avalanche',                'crypto', 'CCC', 'USD'),
('TRX-USD',  'TRON',                     'crypto', 'CCC', 'USD'),
('DOT-USD',  'Polkadot',                 'crypto', 'CCC', 'USD'),
('LINK-USD', 'Chainlink',                'crypto', 'CCC', 'USD'),
('MATIC-USD','Polygon',                  'crypto', 'CCC', 'USD'),
('SHIB-USD', 'Shiba Inu',                'crypto', 'CCC', 'USD'),
('LTC-USD',  'Litecoin',                 'crypto', 'CCC', 'USD'),
('BCH-USD',  'Bitcoin Cash',             'crypto', 'CCC', 'USD'),
('ATOM-USD', 'Cosmos',                   'crypto', 'CCC', 'USD'),
('UNI-USD',  'Uniswap',                  'crypto', 'CCC', 'USD'),
('XLM-USD',  'Stellar',                  'crypto', 'CCC', 'USD')
on conflict (symbol) do nothing;
