# Generated by Django 5.0.6 on 2024-05-20 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Crypto  symbol (e.g., BTC)', max_length=10, unique=True)),
                ('exchange', models.CharField(help_text='Exchange (e.g., NASDAQ)', max_length=255)),
                ('crypto_name', models.CharField(blank=True, help_text='Name of the Crypto (e.g., Bitcoin.)', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Crypto',
                'verbose_name_plural': 'Crypto',
            },
        ),
        migrations.CreateModel(
            name='CryptoPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the crypto price.')),
                ('open', models.DecimalField(decimal_places=2, help_text='Opening price of the crypto on that date.', max_digits=10)),
                ('high', models.DecimalField(decimal_places=2, help_text='Highest price of the crypto on that date.', max_digits=10)),
                ('low', models.DecimalField(decimal_places=2, help_text='Lowest price of the crypto on that date.', max_digits=10)),
                ('close', models.DecimalField(decimal_places=2, help_text='Closing price of the crypto on that date.', max_digits=10)),
                ('crypto', models.ForeignKey(help_text='Foreign key referencing the Crypto table.', on_delete=django.db.models.deletion.CASCADE, to='backtest.crypto')),
            ],
            options={
                'verbose_name': 'Crypto Price',
                'verbose_name_plural': 'Crypto Prices',
            },
        ),
    ]
