# Generated by Django 5.0.6 on 2024-05-30 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0003_crypto_start_date_stock_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Currency ticker symbol (e.g., INR)', max_length=10, unique=True)),
                ('exchange', models.CharField(help_text='Currency (e.g., Indian Rupee)', max_length=255)),
                ('country', models.CharField(blank=True, help_text='Name of the country (e.g., India )', max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, help_text='start of the currency', null=True)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.CreateModel(
            name='ForexPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the forex price.')),
                ('open', models.DecimalField(decimal_places=2, help_text='Opening price of the forex on that date.', max_digits=10)),
                ('high', models.DecimalField(decimal_places=2, help_text='Highest price of the forex on that date.', max_digits=10)),
                ('low', models.DecimalField(decimal_places=2, help_text='Lowest price of the forex on that date.', max_digits=10)),
                ('close', models.DecimalField(decimal_places=2, help_text='Closing price of the forex on that date.', max_digits=10)),
                ('volume', models.BigIntegerField(help_text='Volume of currency traded on that date.')),
                ('forex', models.ForeignKey(help_text='Foreign key referencing the Forex table.', on_delete=django.db.models.deletion.CASCADE, to='backtest.forex')),
            ],
            options={
                'verbose_name': 'Forex Price',
                'verbose_name_plural': 'Forex Prices',
            },
        ),
    ]
