# Generated by Django 5.0.6 on 2024-05-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0005_alter_forex_options_forex_currency_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forex',
            name='exchange',
            field=models.CharField(help_text='Exchange (e.g. NYSE )', max_length=255),
        ),
        migrations.AlterField(
            model_name='forexprice',
            name='volume',
            field=models.BigIntegerField(blank=True, help_text='Volume of currency traded on that date.', null=True),
        ),
    ]
