# Generated by Django 5.0.6 on 2024-06-12 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0006_alter_forex_exchange_alter_forexprice_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forexprice',
            name='forex',
        ),
        migrations.DeleteModel(
            name='Forex',
        ),
        migrations.DeleteModel(
            name='ForexPrice',
        ),
    ]
