# Generated by Django 5.0.6 on 2024-05-14 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Stock ticker symbol (e.g., AAPL)', max_length=10, unique=True)),
                ('exchange', models.CharField(help_text='Stock exchange (e.g., NASDAQ)', max_length=255)),
                ('company_name', models.CharField(blank=True, help_text='Name of the company (e.g., Apple Inc.)', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the stock price.')),
                ('open', models.DecimalField(decimal_places=2, help_text='Opening price of the stock on that date.', max_digits=10)),
                ('high', models.DecimalField(decimal_places=2, help_text='Highest price of the stock on that date.', max_digits=10)),
                ('low', models.DecimalField(decimal_places=2, help_text='Lowest price of the stock on that date.', max_digits=10)),
                ('close', models.DecimalField(decimal_places=2, help_text='Closing price of the stock on that date.', max_digits=10)),
                ('volume', models.BigIntegerField(help_text='Volume of shares traded on that date.')),
                ('stock', models.ForeignKey(help_text='Foreign key referencing the Stock table.', on_delete=django.db.models.deletion.CASCADE, to='backtest.stock')),
            ],
            options={
                'verbose_name': 'Stock Price',
                'verbose_name_plural': 'Stock Prices',
            },
        ),
    ]
