# Generated by Django 5.0.6 on 2024-05-21 01:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0002_crypto_cryptoprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='start of the crypto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='start of the stock'),
            preserve_default=False,
        ),
    ]
