# Generated by Django 5.0.6 on 2024-05-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0004_forex_forexprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forex',
            options={'verbose_name': 'Forex', 'verbose_name_plural': 'Forex'},
        ),
        migrations.AddField(
            model_name='forex',
            name='currency_name',
            field=models.CharField(default='', help_text='Currency (e.g., Indian Rupee)', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forex',
            name='exchange',
            field=models.CharField(help_text='Exchange (e.g., NYSE)', max_length=255),
        ),
    ]
